# Generated by Django 4.0.4 on 2022-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_speciality_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='preview',
        ),
        migrations.AddField(
            model_name='stream',
            name='preview',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
