# Generated by Django 4.0.4 on 2022-10-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_speciality_preview_stream_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='preview',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
