# Generated by Django 4.0.4 on 2022-10-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_programm_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='programm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
