# Generated by Django 4.0.4 on 2022-11-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='USERNAME_FIELD',
        ),
    ]
