# Generated by Django 4.0.4 on 2022-11-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_rename_login_user_username_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='USERNAME_FIELD',
            new_name='login',
        ),
    ]
