# Generated by Django 4.0.4 on 2022-12-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_profile_alter_teacher_user'),
        ('StudentApp', '0007_alter_letter_from_user_alter_letter_to_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
