# Generated by Django 4.0.4 on 2023-01-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login',
        ),
    ]
