# Generated by Django 4.0.4 on 2023-03-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_profile_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
