# Generated by Django 4.0.4 on 2023-03-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0012_profile_teacher_alter_letter_from_user_and_more'),
        ('MainApp', '0014_remove_teacher_subject_remove_teacher_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
