# Generated by Django 4.0.4 on 2022-12-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_rename_username_field_user_login'),
        ('StudentApp', '0003_subjectquestion_studentquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='MainApp.user')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='MainApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='FileInLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='letters')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='StudentApp.letter')),
            ],
        ),
    ]
