# Generated by Django 4.0.4 on 2022-12-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0004_letter_fileinletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='to',
        ),
        migrations.DeleteModel(
            name='FileInLetter',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
