# Generated by Django 4.0.4 on 2022-12-05 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_profile_alter_teacher_user'),
        ('StudentApp', '0006_letter_fileinletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='MainApp.profile'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='MainApp.profile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='MainApp.profile'),
        ),
    ]
