# Generated by Django 4.0.4 on 2023-01-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_profile_login'),
        ('StudentApp', '0007_alter_letter_from_user_alter_letter_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='MainApp.subject'),
        ),
        migrations.DeleteModel(
            name='SubjectQuestion',
        ),
    ]
