# Generated by Django 4.0.4 on 2023-01-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0008_studentquestion_subject_delete_subjectquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='to',
        ),
        migrations.DeleteModel(
            name='FileInLetter',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
