# Generated by Django 4.0.4 on 2023-01-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_remove_profile_login'),
        ('StudentApp', '0009_remove_letter_from_user_remove_letter_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_letters', to='MainApp.profile')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_letters', to='MainApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FileInLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='letters')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='StudentApp.letter')),
            ],
        ),
    ]
